/*
 * Copyright (C) 2014 Vincent Kruger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package gamemanager;

/**
 *
 * @author Vincent Kruger
 */
public class TeamResultsPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeamResultsPanel
     */
    public TeamResultsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        team1Goals = new javax.swing.JFormattedTextField();
        team2Goals = new javax.swing.JFormattedTextField();
        team1ComboBox = new javax.swing.JComboBox();
        team2ComboBox = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(534, 52));
        setMinimumSize(new java.awt.Dimension(534, 52));

        team1Goals.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        team1Goals.setText("0");
        team1Goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1GoalsActionPerformed(evt);
            }
        });

        team2Goals.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        team2Goals.setText("0");
        team2Goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2GoalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(team1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(team1Goals, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(team2Goals, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(team2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(team1Goals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(team2Goals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(team1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(team2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void team1GoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1GoalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team1GoalsActionPerformed

    private void team2GoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2GoalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team2GoalsActionPerformed

    /** Adds the team names in to the combo boxes
     * 
     * @param teams the team manager instance that holds all the teams
     */
    public void addTeams(TeamManager teams) {
        for (int i = 0; i < teams.length; ++i) {
            team1ComboBox.addItem(teams.getTeam(i).getName());
            team2ComboBox.addItem(teams.getTeam(i).getName());
        }
    }

    /** gets the results from the results panel
     * 
     * @return  list of the team names and results
     */
    public Object[] getResults() {
        return new Object[] {team1ComboBox.getSelectedItem(), 
            team2ComboBox.getSelectedItem(), team1Goals.getText(),
            team2Goals.getText()};
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox team1ComboBox;
    private javax.swing.JFormattedTextField team1Goals;
    private javax.swing.JComboBox team2ComboBox;
    private javax.swing.JFormattedTextField team2Goals;
    // End of variables declaration//GEN-END:variables
}
